# Generated by Django 4.1.1 on 2022-09-21 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('currency', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='currencies.currency')),
            ],
        ),
    ]
