# Generated by Django 4.1.1 on 2022-09-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='buy_price',
            field=models.DecimalField(decimal_places=70, max_digits=70),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sell_price',
            field=models.DecimalField(decimal_places=70, max_digits=70),
        ),
    ]
