# Generated by Django 4.1.1 on 2022-09-18 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('transactions', '0003_alter_transaction_buy_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='crn', to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='crn2', to='currencies.currency'),
        ),
    ]
