# Generated by Django 4.1.1 on 2022-09-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_currency_transaction_currency_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=70),
            preserve_default=False,
        ),
    ]
